### ISSUE TITLE
Deprecate rc-radio

### ISSUE THREAD

**Issue by benjycui** [react-component/radio#4]

**Comment by benjycui** [comment]
已废弃，并确认了 antd 和 antd-mobile 都没有使用到 rc-radio。

**Comment by benjycui** [comment]
```bash
deprecate rc-radio@* rc-radio is deprecated, please use rc-checkbox instead.
```

**Comment by DogAndHerDude** [comment]
Really? You just removed this from the NPM registry just like that?
My CI pipeline builds for the staging app have been failing because of this. 

And no, I cannot get away with just using the rc-checkbox. Having to write additonal logic surrounding that would be just unnecessary.

**Comment by paranoidjk** [comment]
@Forestdev I think npm deprecate won't remove the package, just add a warning message in cli see https://unpkg.com/rc-radio@2.0.1/

**Comment by benjycui** [comment]
Actually, rc-radio haven't been maintained for a long time..
